FROM tarantool/tarantool:1.7

COPY deps.sh /opt/tarantool/

RUN set -x \
    && apk add --no-cache --virtual .build-deps \
       git bash cmake make gcc musl-dev \
    && cd /opt/tarantool && ./deps.sh \
    && : "---------- remove build deps ----------" \
    && apk del .build-deps


COPY *.lua /opt/tarantool/
